
services:
  backend:
    environment:
      DJANGO_DEBUG: "1"
    volumes:
      - ./backend:/app

  nginx:
    volumes:
      - ./frontend:/srv/frontend:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
