# Generated by Django 5.1.15 on 2026-08-12 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_match_points_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_block',
                'indexes': [models.Index(fields=['blocker'], name='chat_block_blocker_b7f550_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='no_self_block')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Message'), ('invite', 'Invitation'), ('system', 'Systeme')], default='text', max_length=8)),
                ('body', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='game.match')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['recipient', 'sender', '-created_at'], name='chat_messag_recipie_e25cde_idx'), models.Index(fields=['recipient', 'read_at'], name='chat_messag_recipie_aa591b_idx')],
            },
        ),
    ]
