# Generated by Django 5.1.15 on 2026-08-12 09:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('remote', 'A distance')], default='local', max_length=8)),
                ('state', models.CharField(choices=[('registration', 'Inscriptions'), ('running', 'En cours'), ('finished', 'Termine')], default='registration', max_length=12)),
                ('size', models.PositiveSmallIntegerField(default=4)),
                ('points_to_win', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_tournament',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=24)),
                ('seed_index', models.PositiveSmallIntegerField(default=0)),
                ('eliminated', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_tournament_player',
                'ordering': ['seed_index', 'joined_at'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='game.tournamentplayer'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('remote', 'A distance')], default='local', max_length=8)),
                ('state', models.CharField(choices=[('pending', 'A determiner'), ('lobby', 'En attente'), ('running', 'En cours'), ('finished', 'Terminee'), ('aborted', 'Abandonnee')], default='lobby', max_length=10)),
                ('points_to_win', models.PositiveSmallIntegerField(default=5)),
                ('seed', models.BigIntegerField(default=0)),
                ('player1_alias', models.CharField(blank=True, default='', max_length=24)),
                ('player2_alias', models.CharField(blank=True, default='', max_length=24)),
                ('score1', models.PositiveSmallIntegerField(default=0)),
                ('score2', models.PositiveSmallIntegerField(default=0)),
                ('winner_side', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('by_forfeit', models.BooleanField(default=False)),
                ('round_index', models.PositiveSmallIntegerField(default=0)),
                ('slot_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('total_hits', models.PositiveIntegerField(default=0)),
                ('longest_rally', models.PositiveIntegerField(default=0)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_left', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_right', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='game.tournament')),
            ],
            options={
                'db_table': 'game_match',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'mode'], name='game_match_state_b0d063_idx'), models.Index(fields=['tournament', 'round_index', 'slot_index'], name='game_match_tournam_79162d_idx'), models.Index(fields=['-finished_at'], name='game_match_finishe_08b2f8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentplayer',
            constraint=models.UniqueConstraint(fields=('tournament', 'alias'), name='unique_alias_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('tournament', 'user'), name='unique_user_per_tournament'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['state', '-created_at'], name='game_tourna_state_9005e9_idx'),
        ),
    ]
