# Generated by Django 5.1.15 on 2026-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='points_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
